collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5721782
  brandStrength: 1
  lightness: 0.4731183
  brandColors:
    - '#0A1B2C'
    - '#314253'
    - '#087CB1'
    - '#DBDCD7'
    - '#6C94B8'
  rhythmicContrast: 0.3387097
typography_spectrum: 0.1615318
layout_spectrum: 0
name: 1pg
